// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxZHLClNlLaTMzH1JJ-QEFwNgKuV8SN0',
    appId: '1:539060516356:web:5fdf143faf74f0dd192751',
    messagingSenderId: '539060516356',
    projectId: 'whatsapp-clone-11374',
    authDomain: 'whatsapp-clone-11374.firebaseapp.com',
    storageBucket: 'whatsapp-clone-11374.appspot.com',
    measurementId: 'G-D2V5NNZNQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIx4vA7UzQIegFKVhsoghJXbX3edrDQHc',
    appId: '1:539060516356:android:1ac206200057992b192751',
    messagingSenderId: '539060516356',
    projectId: 'whatsapp-clone-11374',
    storageBucket: 'whatsapp-clone-11374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDz4tmyhPfx56KeSyIwOj4tWFe2sfs-DM',
    appId: '1:539060516356:ios:c7e73bdc258757d7192751',
    messagingSenderId: '539060516356',
    projectId: 'whatsapp-clone-11374',
    storageBucket: 'whatsapp-clone-11374.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDz4tmyhPfx56KeSyIwOj4tWFe2sfs-DM',
    appId: '1:539060516356:ios:635d560b507b0ae4192751',
    messagingSenderId: '539060516356',
    projectId: 'whatsapp-clone-11374',
    storageBucket: 'whatsapp-clone-11374.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
